name: ViaMaintenance
version: 1.0.0
main: ru.viamaintenance.ViaMaintenance
api-version: 1.16 # Adjust if needed for your server version
authors: [wryiun, ViaTeam]
description: Simple maintenance plugin

commands:
  maintenance:
    description: Toggles server maintenance mode.
    usage: /<command> [on|off]
    permission: viamaintenance.admin
    aliases: [maint, vm]

permissions:
  viamaintenance.admin:
    description: Allows toggling maintenance mode.
    default: op
  viamaintenance.bypass:
    description: Allows joining the server during maintenance.
    default: op
